apiVersion: 1.0
kind: Job
metadata:
  name: OrdersBase
  description: Base Job for Orders
spec:
  variables:
  -
    variableName: ConnectionString
    value: server=abc
    readOnly: true
    locked: true
    hidden: true
