apiVersion: v1.0
kind: job
metadata:
  name: OrdersBase
  description: Base Job for Orders
spec:
  variables:
  -
    variableName: ConnectionString
    value: server=abc
    readOnly: true
    locked: true
    hidden: true
