apiVersion: 1.0
kind: cli
metadata:
  name: ShippedReport
  description: On Demand Shipped Report
spec:
  shell: sh
  script: |
    echo "Emailing Shipping Report..."
    sleep 10
    echo "Shipping report emailed."
  actions:
  -
    action: cronSchedule
    cronExpression: "0 8 * * *"
  variables:
  -
    variableName: Region
    value: South
    minimumLength: 1
    maximumLength: 50
    prompt: Please enter the region
    inputType: Text
  -
    variableName: Division
    value: Western
    minimumLength: 1
    maximumLength: 10
    prompt: Please enter the division
    inputType: Text
  -
    variableName: StartDate
    value: 2026-07-01
    prompt: Please enter the start date
    inputType: Default
  -
    variableName: EndDate
    value: 2026-07-31
    prompt: Please enter the end date
    inputType: Default


